name: Default Process
description: Default Action Process For All Jobs

runs: 
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Node Cache
      uses: actions/cache@v3
      id: cache
      with:
        path: /opt/hostedtoolcache/Node/
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: npm-

    - name: Install Dependencies
      shell: bash
      run: |


        npm i
        npx playwright install
        
    - name: Restaurar Cache do npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Salvar Cache do npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}